# Generated by Django 5.2.1 on 2025-06-02 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=50)),
                ('nick', models.CharField(max_length=50)),
                ('gender', models.CharField(default='남자', max_length=10)),
                ('hobby', models.CharField(default='게임', max_length=50)),
            ],
        ),
    ]
