# Generated by Django 5.2.1 on 2025-06-11 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_alter_comment_cdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='cpuw',
            new_name='cpw',
        ),
    ]
