# Generated by Django 5.2.1 on 2025-05-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('major', models.CharField(max_length=100)),
                ('grade', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(max_length=30)),
            ],
        ),
    ]
