# Generated by Django 5.2.1 on 2025-06-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='bdate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='board',
            name='bstep',
            field=models.IntegerField(default=0),
        ),
    ]
